service: serverless-crud-local

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: local
  region: us-east-1
  environment:
    TABLE_NAME: ItemsTable
    TOPIC_ARN: arn:aws:sns:us-east-1:000000000000:NotifyTopic
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - sns:*
          Resource: "*"

plugins:
  - serverless-localstack
  - serverless-offline

custom:
  localstack:
    stages:
      - local
    host: http://localhost  # Importante para conectar no Docker
    edgePort: 4566
    autostart: true
    lambda:
      # Melhora performance em dev
      mountCode: true

functions:
  # --- CRUD ---
  createItem:
    handler: src/create.handler
    events:
      - http:
          path: items
          method: post
  
  listItems:
    handler: src/list.handler
    events:
      - http:
          path: items
          method: get

  getItem:
    handler: src/get.handler
    events:
      - http:
          path: items/{id}
          method: get

  updateItem:
    handler: src/update.handler
    events:
      - http:
          path: items/{id}
          method: put

  deleteItem:
    handler: src/delete.handler
    events:
      - http:
          path: items/{id}
          method: delete

  # --- SUBSCRIBER (Requisito 3) ---
  notificationSubscriber:
    handler: src/subscriber.handler
    events:
      - sns:
          arn: arn:aws:sns:us-east-1:000000000000:NotifyTopic
          topicName: NotifyTopic

resources:
  Resources:
    # Cria a Tabela DynamoDB [cite: 20]
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1